/** データセットから、place に焼かれる Luau / TypeScript を組み立てる。
 *
 * ここが出荷の正を作る。生成物は git に載って PR の diff に出るので、行の順序も
 * インデントも入力が同じなら常に同じになるように書く（揺れると差分が読めなくなる）。
 */

const RESERVED_TYPE_NAMES = new Set(["Row", "Scalars"]);

function pascal(name) {
	return name.charAt(0).toUpperCase() + name.slice(1);
}

function luauString(value) {
	const escaped = value
		.replace(/\\/g, "\\\\")
		.replace(/"/g, '\\"')
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t");
	return `"${escaped}"`;
}

function luauValue(value) {
	if (typeof value === "string") return luauString(value);
	if (typeof value === "boolean") return value ? "true" : "false";
	return String(value);
}

/** enum 列の型名。Row / Scalars と衝突したら列名側を退ける（生成物が壊れるより読みにくい方がまし） */
function enumTypeName(column) {
	const name = pascal(column.name);
	return RESERVED_TYPE_NAMES.has(name) ? `${name}Value` : name;
}

function columnType(column) {
	switch (column.type) {
		case "number":
		case "integer":
			return "number";
		case "boolean":
			return "boolean";
		case "enum":
			return enumTypeName(column);
		default:
			return "string";
	}
}

function enumColumns(sheet) {
	return sheet.columns.filter((column) => column.type === "enum");
}

/** --!strict は先頭になければ効かないので、説明のコメントより前に置く */
function luauHeader(sheet, strict) {
	const lines = [strict ? "--!strict" : "--!nocheck", `-- Generated by rosheet from sheet "${sheet.name}". Do not edit by hand.`];
	if (sheet.description !== "") lines.push(`-- ${sheet.description}`);
	lines.push("");
	return lines;
}

function fieldLines(sheet, render) {
	const lines = [];
	for (const column of sheet.columns) {
		if (column.description !== "") lines.push(render.comment(column.description));
		lines.push(render.field(column));
	}
	return lines;
}

function generateLuau(sheet, value, options = {}) {
	const strict = options.strict !== false;
	const lines = luauHeader(sheet, strict);

	for (const column of enumColumns(sheet))
		lines.push(`export type ${enumTypeName(column)} = ${column.values.map(luauString).join(" | ")}`, "");

	const shape = sheet.kind === "scalars" ? "Scalars" : "Row";
	lines.push(
		`export type ${shape} = {`,
		...fieldLines(sheet, {
			comment: (text) => `\t-- ${text}`,
			field: (column) => `\t${column.name}: ${columnType(column)},`,
		}),
		"}",
		"",
	);

	if (sheet.kind === "scalars") {
		lines.push("local scalars: Scalars = {");
		for (const column of sheet.columns) lines.push(`\t${column.name} = ${luauValue(value[column.name])},`);
		lines.push("}", "", "return table.freeze(scalars)", "");
		return lines.join("\n");
	}

	lines.push("local rows: { Row } = {");
	for (const row of value) {
		lines.push("\t{");
		for (const column of sheet.columns) lines.push(`\t\t${column.name} = ${luauValue(row[column.name])},`);
		lines.push("\t},");
	}
	lines.push("}", "");

	// 行ごとに freeze するのは、配列だけ freeze しても中の行は書き換えられてしまうため
	lines.push("for _, row in rows do", "\ttable.freeze(row)", "end", "table.freeze(rows)", "");

	if (sheet.key === null) {
		lines.push("return table.freeze({", "\trows = rows,", "})", "");
		return lines.join("\n");
	}

	const index = `by${pascal(sheet.key)}`;
	lines.push(
		`local ${index}: { [string]: Row } = {}`,
		"for _, row in rows do",
		`\t${index}[row.${sheet.key}] = row`,
		"end",
		`table.freeze(${index})`,
		"",
		"return table.freeze({",
		"\trows = rows,",
		`\t${index} = ${index},`,
		`\tget = function(${sheet.key}: string): Row?`,
		`\t\treturn ${index}[${sheet.key}]`,
		"\tend,",
		"})",
		"",
	);
	return lines.join("\n");
}

function generateDts(sheet) {
	const lines = [`// Generated by rosheet from sheet "${sheet.name}". Do not edit by hand.`];
	if (sheet.description !== "") lines.push(`// ${sheet.description}`);
	lines.push("");

	for (const column of enumColumns(sheet))
		lines.push(`export type ${enumTypeName(column)} = ${column.values.map((v) => JSON.stringify(v)).join(" | ")};`, "");

	const shape = sheet.kind === "scalars" ? "Scalars" : "Row";
	lines.push(
		`export interface ${shape} {`,
		...fieldLines(sheet, {
			comment: (text) => `\t/** ${text} */`,
			field: (column) => `\treadonly ${column.name}: ${columnType(column)};`,
		}),
		"}",
		"",
	);

	if (sheet.kind === "scalars") {
		for (const column of sheet.columns) lines.push(`export declare const ${column.name}: ${columnType(column)};`);
		lines.push("");
		return lines.join("\n");
	}

	lines.push("export declare const rows: readonly Row[];");
	if (sheet.key !== null) {
		const index = `by${pascal(sheet.key)}`;
		lines.push(`export declare const ${index}: { readonly [${sheet.key}: string]: Row | undefined };`);
		lines.push(`export declare function get(${sheet.key}: string): Row | undefined;`);
	}
	lines.push("");
	return lines.join("\n");
}

module.exports = { generateLuau, generateDts, pascal, luauString, enumTypeName, columnType };
