/** 生成物をディスクへ書く / ディスクと突き合わせる。
 *
 * --check は CI 用で、生成物が DataStore から引いた値と一致しているかだけを見る。
 * ネットワークは要らない（引いた結果は data/ ではなく生成物そのものに残っているため）。
 */

const { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, rmSync } = require("fs");
const path = require("path");
const { generateLuau, generateDts } = require("./codegen");
const { createResolver, resolveDataset } = require("./assets");

const MARKER = "Generated by rosheet";

function filesFor(schema, dataset, format, resolver, options = {}) {
	// asset 列の rocas:// はここで実 ID になる。place に焼かれるのは解決済みの値だけ
	const resolved = resolveDataset(schema, dataset, resolver);
	const source = options.source;
	const files = [];
	for (const sheet of schema.sheets) {
		const value = resolved[sheet.name];
		files.push({
			name: `${sheet.name}.luau`,
			// roblox-ts では型は .d.ts が持つので、Luau 側を strict にしても二重に書くだけになる
			content: generateLuau(sheet, value, { strict: format === "luau", source }),
		});
		if (format === "roblox-ts") files.push({ name: `${sheet.name}.d.ts`, content: generateDts(sheet, { source }) });
	}
	return files;
}

/** rosheet が前に書いたファイルだけを消す対象にする。人が置いたファイルは触らない */
function staleFiles(outDir, keep) {
	if (!existsSync(outDir)) return [];
	return readdirSync(outDir).filter((name) => {
		if (keep.has(name)) return false;
		if (!name.endsWith(".luau") && !name.endsWith(".d.ts")) return false;
		return readFileSync(path.join(outDir, name), "utf8").includes(MARKER);
	});
}

function normalizeEol(text) {
	return text.replace(/\r\n/g, "\n");
}

function write(schema, dataset, config, cwd = process.cwd(), options = {}) {
	const outDir = path.resolve(cwd, config.output.dir);
	// 生成物の出力先は書く側が作る。先に走る別のコマンドが作っている前提に乗らない
	mkdirSync(outDir, { recursive: true });

	const files = filesFor(schema, dataset, config.output.format, createResolver(cwd), options);
	const written = [];
	for (const file of files) {
		const target = path.join(outDir, file.name);
		const existing = existsSync(target) ? normalizeEol(readFileSync(target, "utf8")) : null;
		if (existing === file.content) continue;
		writeFileSync(target, file.content, "utf8");
		written.push(file.name);
	}

	const removed = staleFiles(outDir, new Set(files.map((file) => file.name)));
	for (const name of removed) rmSync(path.join(outDir, name));

	return { outDir, written, removed, total: files.length };
}

/** 差分の一覧を返す。空なら一致 */
function check(schema, dataset, config, cwd = process.cwd(), options = {}) {
	const outDir = path.resolve(cwd, config.output.dir);
	const files = filesFor(schema, dataset, config.output.format, createResolver(cwd), options);
	const problems = [];

	for (const file of files) {
		const target = path.join(outDir, file.name);
		if (!existsSync(target)) {
			problems.push(`${file.name}: missing`);
			continue;
		}
		if (normalizeEol(readFileSync(target, "utf8")) !== file.content) problems.push(`${file.name}: does not match the current values`);
	}

	for (const name of staleFiles(outDir, new Set(files.map((file) => file.name))))
		problems.push(`${name}: left over from a sheet the schema no longer has`);

	return problems;
}

module.exports = { MARKER, filesFor, write, check };
