/** plugin/src/*.luau を 1 つの .rbxmx にまとめて Studio の Plugins フォルダへ置く。
 *
 * 束ねずに ModuleScript の木のまま入れる。バンドラで require を書き換えると、Studio 側で出た
 * エラーの行番号がリポジトリのファイルと合わなくなり、UI の作り込みで一番効く手掛かりを失う。
 */

const { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } = require("fs");
const path = require("path");
const { render } = require("./rbxmx");

const PLUGIN_NAME = "rosheet";
const DEFAULT_PLUGIN_FILE = `${PLUGIN_NAME}.rbxmx`;
const SOURCE_DIR = path.join(__dirname, "..", "plugin", "src");
const ENTRY = "init.server.luau";

function robloxStudioPluginsDir(env = process.env, platform = process.platform) {
	if (platform === "win32" && env.LOCALAPPDATA) return path.join(env.LOCALAPPDATA, "Roblox", "Plugins");
	if (platform === "darwin" && env.HOME) return path.join(env.HOME, "Documents", "Roblox", "Plugins");
	return null;
}

/** rosheet.toml の値をプラグインへ渡す唯一の経路。プラグインは .toml を読めない */
function configModule(config) {
	const lines = [
		"--!strict",
		"-- Generated by rosheet from rosheet.toml. Do not edit by hand.",
		"",
		"return table.freeze({",
		`\tdatastore = ${JSON.stringify(config.project.datastore)},`,
		`\tscope = ${config.project.scope === undefined ? "nil" : JSON.stringify(config.project.scope)},`,
		`\tschemaPath = ${JSON.stringify(config.schema.path)},`,
		"})",
		"",
	];
	return lines.join("\n");
}

function moduleChildren(config) {
	const children = [{ className: "ModuleScript", name: "Config", source: configModule(config) }];

	for (const file of readdirSync(SOURCE_DIR).sort()) {
		if (file === ENTRY || !file.endsWith(".luau")) continue;
		children.push({
			className: "ModuleScript",
			name: path.basename(file, ".luau"),
			source: readFileSync(path.join(SOURCE_DIR, file), "utf8"),
		});
	}

	return children;
}

function buildPlugin(config) {
	if (!existsSync(path.join(SOURCE_DIR, ENTRY)))
		throw new Error(`プラグインの本体がまだ無い: ${path.join(SOURCE_DIR, ENTRY)}`);

	return render({
		className: "Script",
		name: PLUGIN_NAME,
		source: readFileSync(path.join(SOURCE_DIR, ENTRY), "utf8"),
		children: moduleChildren(config),
	});
}

function writePlugin(config, options = {}) {
	const cwd = options.cwd ?? process.cwd();
	const pluginsDir = robloxStudioPluginsDir();

	const target =
		options.output !== null && options.output !== undefined
			? path.resolve(cwd, options.output)
			: pluginsDir === null
				? path.resolve(cwd, DEFAULT_PLUGIN_FILE)
				: path.join(pluginsDir, DEFAULT_PLUGIN_FILE);

	const dir = path.dirname(target);
	if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
	writeFileSync(target, buildPlugin(config), "utf8");

	return { path: target, intoStudio: pluginsDir !== null && target.startsWith(pluginsDir) };
}

module.exports = { PLUGIN_NAME, DEFAULT_PLUGIN_FILE, SOURCE_DIR, robloxStudioPluginsDir, buildPlugin, writePlugin, configModule };
